#!/usr/bin/sh

QDLDL_BUILD_STATIC_LIB="OFF"
QDLDL_BUILD_SHARED_LIB="ON"
QDLDL_FLOAT="OFF"
QDLDL_LONG="ON"

cmake -DQDLDL_BUILD_STATIC_LIB=$QDLDL_BUILD_STATIC_LIB -DQDLDL_BUILD_SHARED_LIB=$QDLDL_BUILD_SHARED_LIB -DQDLDL_FLOAT=$QDLDL_FLOAT \
      -DQDLDL_LONG=$QDLDL_LONG -Sqdldl -Bqdldl/build -G "Unix Makefiles" qdldl
make -C qdldl/build -j